### PR TITLE
add check for curl --resolve switch

### PR DESCRIPTION
**Pull request by Prajithp**
Curl version <7.35.0 doesn't support --resolve argument, so added a check for that.

### CODE REVIEW

**Comment by j-schulz** [comment]
I'm sorry, but I think it's not a good idea to support older curl versions.

**Comment by Prajithp** [comment]
But centos 6 comes with curl  version 7.19. Do you have any plan to remove centos 6 support?

**Comment by j-schulz** [comment]
No. But check-http is a remote check, not a localhost check, so it should be possible for you to run the check on a centos 7 machine ;-)

**Comment by Prajithp** [comment]
Okay fine then :)

**Pull request closed without merging**
